stages:
  # - test
  - deploy

# unit-test-job:
#   stage: test
#   script:
#     - echo "Unit tests run successfully"

# e2e:
#   stage: test
#   script:
#     - echo "end2end tests run successfully"

staging.deploy:
  image: ruby:3.1.1
  stage: deploy
  before_script:
  - gem install dpl
  - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - echo -en $"ENVIRONMENT=staging\nSECRET_KEY=$1\nDJANGO_SUPERUSER_PASSWORD=$ADMIN_PASSWORD" > .env
    - dpl --provider=heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_APIKEY --skip-cleanup
    - export HEROKU_API_KEY=$HEROKU_APIKEY
  environment:
    name: staging
    url: $HEROKU_APP_HOST
  only: 
    - develop
  tags:
    - dockerRunner



production.deploy:
  image: ruby:3.1.1
  stage: deploy
  before_script:
  - gem install dpl
  script:
    - export HEROKU_API_KEY=$HEROKU_APIKEY
  environment:
    name: staging
    url: $HEROKU_APP_HOST
  only: 
    - main
  tags:
    - dockerRunner