stages:
  # - test
  - deploy

# unit-test-job:
#   stage: test
#   script:
#     - echo "Unit tests run successfully"

# e2e:
#   stage: test
#   script:
#     - echo "end2end tests run successfully"

deploy:
  image: ruby:3.1.1
  stage: deploy
  before_script:
  - gem install dpl
  - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - echo -en $"ENVIRONMENT=staging\nSECRET_KEY=$1" > .env
    - dpl --provider=heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_APIKEY --skip-cleanup
    - export HEROKU_API_KEY=$HEROKU_APIKEY
  environment:
    name: staging
    url: $HEROKU_APP_HOST
  only: 
    - main
    - develop
  tags:
    - dockerRunner
  artifacts:
    untracked: true
    expire_in: 30 days

deploy.production:
  stage: deploy
  image: alpine:latest
  script:
    - echo -en $"ENVIRONMENT=production\nSECRET_KEY=$1\nDJANGO_SUPERUSER_PASSWORD=$ADMIN_PASSWORD" > .env
    - rsync -azv --stats -e "ssh -i $LIGHTSAIL_SSH_KEY"  ./ ubuntu@3.67.179.62:/home/ubuntu/ChefsGrub/live
    - ssh -i $LIGHTSAIL_SSH_KEY ubuntu@3.67.179.62 'cd ChefsGrub/live; make server;'
  environment:
    name: production
    url: $AWS_APP_HOST
  only: 
    - main
  tags:
    - dockerRunner
  artifacts:
    untracked: true
    expire_in: 30 days
